### ISSUE TITLE
...

### ISSUE THREAD

**Issue by amit717628** [miramallows/patreon-discord#4]
allPatronsSocials = [...allPatronsSocials, ...response.included]
                                                                   ^

TypeError: response.included is not iterable
    at Campaign._scrapeData (/root/anti/node_modules/patreon-discord/class/campaign.js:23:68)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Campaign.fetchPatrons (/root/anti/node_modules/patreon-discord/class/campaign.js:56:76)
    at async Function.findOrCreatePatron (/root/anti/src/utils/patron.js:11:31)
    at async messageCreate.run (/root/anti/src/events/Client/messageCreate.js:99:9)

**Comment by taahamahdi** [comment]
Looks like it was an issue on Patreon's end. It's working now

**Comment by FraglyG** [comment]
I'm getting this as well, anyone have a fix yet?
